##VARIABLE STUDY
OPTIMIZER = 'adam'
FUNCTION_LOSS = "mean_squared_error"
NUMBER_NEURONE_HIDDEN_LAYER_ANN = 16

##LAYER
NUMBER_HIDDEN_LAYER = 3


##NEURONE
NUMBER_NEURONE_OUTPUT = 1


##FUNCTION
FUNCTION_ACTIVATION = "relu"
FUNCTION_OUTPOUT = "sigmoid"
BATCH_SIZE = 32

##OTHER
NUMBER_EPOCH = 15
ANN_NUMBER_INPUT = 11

##KERAS
METRIC = ["acc"]

##PYTROCH
THRESHOLD_TRUE = 0.5

##DATA MANAGER
POURCANT_DATA_TEST = 0.2
POURCANT_DATA_TRAIN = 1 - POURCANT_DATA_TEST
